# NUMPY



Agenda
Part I: Creating an array and solving basic questions
Part II: Loading a dataset and performing basic data analysis

Part I: Creating an array and solving basic questions

Answers:

### 1. Write a program to create a 1D array having 100 random numbers between 0 to 50

In [118]:
import numpy as np
arr = np.random.randint(0,50,100)
arr

array([49, 23,  5, 29,  7, 39, 10,  7, 22, 15, 48, 18, 25, 11,  4, 38, 19,
       37, 32, 25, 26, 36,  5, 14,  7, 22,  5, 48, 37, 30, 17,  6, 13,  0,
        1, 27,  0, 21, 19, 42,  1, 21,  8, 49, 30, 40, 26, 14, 48, 48, 10,
       38, 36, 21, 19,  8, 40, 10,  0, 44, 47, 16,  0, 46,  1, 30, 45,  6,
       34, 19, 39, 17, 30, 10,  2,  9, 35,  5, 22,  0,  9,  2,  8, 19,  0,
       22, 20, 27, 24,  7,  4, 36, 45, 29,  1, 12, 31,  0, 10, 29])

### 2. Check the size and shape of the array

In [119]:
print(arr.shape)
print(arr.size)

(100,)
100


### 3. Reshape the above array into 20*5 shape and check the shape and size

In [120]:
arr_updated = arr.reshape(20,5)
arr_updated

array([[49, 23,  5, 29,  7],
       [39, 10,  7, 22, 15],
       [48, 18, 25, 11,  4],
       [38, 19, 37, 32, 25],
       [26, 36,  5, 14,  7],
       [22,  5, 48, 37, 30],
       [17,  6, 13,  0,  1],
       [27,  0, 21, 19, 42],
       [ 1, 21,  8, 49, 30],
       [40, 26, 14, 48, 48],
       [10, 38, 36, 21, 19],
       [ 8, 40, 10,  0, 44],
       [47, 16,  0, 46,  1],
       [30, 45,  6, 34, 19],
       [39, 17, 30, 10,  2],
       [ 9, 35,  5, 22,  0],
       [ 9,  2,  8, 19,  0],
       [22, 20, 27, 24,  7],
       [ 4, 36, 45, 29,  1],
       [12, 31,  0, 10, 29]])

In [121]:
print(arr_updated.shape)
print(arr_updated.size)

(20, 5)
100


### 4.Write a code to check statistical details (min, max, mean values) of the above array

In [122]:
arr_updated.min()

0

In [123]:
arr_updated.max()

49

In [124]:
arr_updated.mean()

20.98

In [125]:
arr_updated.std()

14.97529966311192

## Part II: Loading a dataset and performing basic data analysis

In [97]:
url='https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

In [98]:
iris = np.genfromtxt(url,delimiter=',',dtype=float,usecols=[0,1,2,3])
name=('selaplength','sepalwidth', 'petallength', 'petalwidth')

In [99]:
iris

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

### Numpy Functions:

In [10]:
iris.shape

(150, 4)

In [11]:
iris.size

600

In [42]:
iris[121]

array([5.6, 2.8, 4.9, 2. ])

In [16]:
iris.ndim

2

In [17]:
iris[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [22]:
sepallength=np.array([col[0] for col in iris])
sepallength

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

#### Normalising the array

In [28]:
norm=(sepallength-sepallength.min())/(sepallength.max()-sepallength.min())
norm[:10]

array([0.22222222, 0.16666667, 0.11111111, 0.08333333, 0.19444444,
       0.30555556, 0.08333333, 0.19444444, 0.02777778, 0.16666667])

In [32]:
percentile= np.percentile(sepallength,q=50)
percentile

5.8

In [101]:
np.isnan(iris).sum()

0

#### Addition of null values to check

In [103]:
index_nan = np.random.choice(iris.size, 50, replace=False)
 
iris.ravel()[index_nan] = np.nan 

In [104]:
iris

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, nan],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, nan, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [nan, 3.4, 1.5, 0.2],
       [nan, nan, 1.4, 0.2],
       [4.9, 3.1, 1.5, nan],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, nan],
       [4.8, 3. , 1.4, nan],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, nan, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, nan, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, nan, nan, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, nan, nan, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [105]:
np.isnan(iris).sum()

50